mxnet_variant_str:
  - cpu
  - cu102
mxnet_variant_version:
  - 0.0.20
  - 0.0.30
mxnet_version:
  - 1.8.0
c_compiler:
  - gcc
cxx_compiler:
  - gxx
c_compiler_version:
  - 7
cxx_compiler_version:
  - 7
cudatoolkit_version:
  - 10.2
cuda_compiler_version:
  - 10.2
cudnn_version:
  - 8.1
python_version:
  - 3.8
nccl_version:
  - 2.9
libopencv:  # [win]
  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
