# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "mxnet" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/incubator-mxnet/archive/tags/{{ version }}.tar.gz
  sha256: 976e0193622378b9174d6ff95b8d1e5369e66945c5345a13c642748b51eb9758

build:
  number: 0

requirements:
  script: build-mxnet.sh  # [not win]
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp   # [linux]
  host:
    # GPU requirements
    - cudnn
    - nccl
    - python
    - numpy
    - openblas
    - onednn
    - pip
  run:
    - python

test:
  imports:
    - import mxnet 

about:
  home: http://mxnet.io
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: MXNet is a deep learning framework designed for both efficiency and flexibility
  description: |
    Apache MXNet (incubating) is a deep learning framework designed for both
    efficiency and flexibility. It allows you to mix symbolic and imperative
    programming to maximize efficiency and productivity. At its core, MXNet
    contains a dynamic dependency scheduler that automatically parallelizes both
    symbolic and imperative operations on the fly. A graph optimization layer on
    top of that makes symbolic execution fast and memory efficient. MXNet is
    portable and lightweight, scaling effectively to multiple GPUs and multiple
    machines. MXNet is also more than a deep learning project. It is also a
    collection of blue prints and guidelines for building deep learning systems,
    and interesting insights of DL systems for hackers.
  doc_url: https://mxnet.incubator.apache.org/
  dev_url: https://github.com/apache/incubator-mxnet

extra:
  recipe-maintainers:
    - barry-jin
